# Generated by Django 2.0.3 on 2019-01-01 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20181213_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ratedUsers',
            field=models.ManyToManyField(blank=True, related_name='ratedUsersVideo', to=settings.AUTH_USER_MODEL),
        ),
    ]
